import React from 'react';
import { supabaseServer } from '@/lib/supabase/server';
import { Button } from '@/components/ui/Button';

export default async function AIAutomationDashboard() {
  const [kbCountRes, embeddingCountRes, conversationCountRes, recruiterReqRes, generationsRes, reportsRes] = await Promise.all([
    supabaseServer.from('ai_knowledge_base').select('id', { count: 'exact', head: true }),
    supabaseServer.from('ai_embeddings').select('id', { count: 'exact', head: true }),
    supabaseServer.from('ai_conversations').select('id', { count: 'exact', head: true }),
    supabaseServer.from('recruiter_interactions').select('id', { count: 'exact', head: true }),
    supabaseServer.from('ai_generations').select('*').order('created_at', { ascending: false }).limit(10),
    supabaseServer.from('ai_reports').select('*').order('generated_at', { ascending: false }).limit(5),
  ]);

  const totalKb = kbCountRes.count ?? 0;
  const totalEmbeddings = embeddingCountRes.count ?? 0;
  const totalConversations = conversationCountRes.count ?? 0;
  const totalRecruiter = recruiterReqRes.count ?? 0;
  const generations = generationsRes.data ?? [];
  const reports = reportsRes.data ?? [];

  return (
    <div className="p-6 space-y-6">
      <div>
        <h1 className="text-2xl font-semibold">AI Automation Dashboard</h1>
        <p className="mt-2 text-sm text-muted-foreground">Centralized AI workflows, usage, and generated content.</p>
      </div>

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <div className="rounded-3xl border border-border bg-surface p-6">
          <p className="text-sm uppercase tracking-[0.3em] text-muted-foreground">Total Indexed Documents</p>
          <p className="mt-4 text-3xl font-semibold">{totalKb}</p>
        </div>
        <div className="rounded-3xl border border-border bg-surface p-6">
          <p className="text-sm uppercase tracking-[0.3em] text-muted-foreground">Total Embeddings</p>
          <p className="mt-4 text-3xl font-semibold">{totalEmbeddings}</p>
        </div>
        <div className="rounded-3xl border border-border bg-surface p-6">
          <p className="text-sm uppercase tracking-[0.3em] text-muted-foreground">Total AI Conversations</p>
          <p className="mt-4 text-3xl font-semibold">{totalConversations}</p>
        </div>
        <div className="rounded-3xl border border-border bg-surface p-6">
          <p className="text-sm uppercase tracking-[0.3em] text-muted-foreground">Recruiter Requests</p>
          <p className="mt-4 text-3xl font-semibold">{totalRecruiter}</p>
        </div>
      </div>

      <div className="rounded-3xl border border-border bg-surface p-6">
        <h2 className="text-lg font-semibold">Automation Jobs</h2>
        <p className="mt-2 text-sm text-muted-foreground">Recent AI generation jobs and status.</p>

        <div className="mt-4 space-y-3">
          {generations.length === 0 ? (
            <p className="text-sm text-muted-foreground">No generation records found.</p>
          ) : (
            generations.map((g: any) => (
              <div key={g.id} className="flex items-center justify-between rounded-xl border p-3">
                <div>
                  <p className="font-medium">{g.generation_type} — {g.source_type || 'system'}</p>
                  <p className="text-sm text-muted-foreground">Status: {g.status}</p>
                </div>
                <div>
                  <a href={`/admin/ai/generation/${g.id}`} className="text-sm text-primary">View</a>
                </div>
              </div>
            ))
          )}
        </div>
      </div>

      <div className="rounded-3xl border border-border bg-surface p-6">
        <h2 className="text-lg font-semibold">Scheduled Reports</h2>
        <p className="mt-2 text-sm text-muted-foreground">Recent reports generated by AI.</p>

        <div className="mt-4 space-y-3">
          {reports.length === 0 ? (
            <p className="text-sm text-muted-foreground">No reports yet.</p>
          ) : (
            reports.map((r: any) => (
              <div key={r.id} className="flex items-center justify-between rounded-xl border p-3">
                <div>
                  <p className="font-medium">{r.title || r.report_type}</p>
                  <p className="text-sm text-muted-foreground">Period: {r.period}</p>
                </div>
                <div>
                  <a href={`/admin/ai/report/${r.id}`} className="text-sm text-primary">View</a>
                </div>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );
}
